pool: Default
jobs:
- job: build
  steps:
  - script: mvn clean install
  
- job: sast_scan
  steps:
  - script: /root/findsecbugs.sh -xargs -progress -html  -h -output $PWD/findsecbugs_report.html target/dvja-1.0-SNAPSHOT.war || true
  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(Build.SourcesDirectory)'
      contents: '*.json'
      targetFolder: $(Build.ArtifactStagingDirectory)
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: sast_results

- job: sca_scan
  steps:
  - script: /root/dependency-check/bin/dependency-check.sh --project "DVJA" --scan "target/dvja-1.0-SNAPSHOT.war" --format "HTML" --disableBundleAudit --disableRubygems --disableNuspec || true
  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(Build.SourcesDirectory)'
      contents: '*.json'
      targetFolder: $(Build.ArtifactStagingDirectory)
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: sca_results
